"""
Custom middleware for request timing and logging.
Logs every API request with response time for performance monitoring.
"""

import time
import logging

logger = logging.getLogger('request_timing')


class RequestTimingMiddleware:
    """
    Middleware to measure and log request processing time.

    Logs format:
    "GET /api/v1/studies/search?q=... HTTP/1.1" 200 15053 [125ms]

    Performance impact: <1ms per request (negligible)
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        """Process request with timing measurement and logging.

        This method is called for every HTTP request processed by Django.
        It measures the total request processing time and logs it for monitoring.

        Args:
            request: Django HttpRequest object containing request details

        Returns:
            HttpResponse: The response generated by the view or subsequent middleware

        Example Log Output:
            "GET /api/v1/studies/search?q=test HTTP/1.1" 200 15053 [125ms]

        Performance Impact:
            <1ms overhead per request (time.time() calls are very fast)
        """
        # Record start time
        start_time = time.time()

        # Process request through view and other middleware
        response = self.get_response(request)

        # Calculate duration in milliseconds
        duration_ms = (time.time() - start_time) * 1000

        # Get response size for monitoring
        content_length = len(response.content) if hasattr(response, 'content') else 0

        # Log request with timing (Apache Combined Log Format + timing)
        logger.info(
            f'"{request.method} {request.get_full_path()} '
            f'{request.META.get("SERVER_PROTOCOL", "HTTP/1.1")}" '
            f'{response.status_code} {content_length} '
            f'[{duration_ms:.0f}ms]'
        )

        return response
