# Generated by Django 5.2.8 on 2025-11-25 09:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="study",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="medical_exa_search__d9c92c_gin"
            ),
        ),
    ]
