# Generated by Django 5.0 on 2025-11-25 12:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('task_id', models.CharField(db_index=True, help_text='唯一任務標識', max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='創建用戶 ID', max_length=100)),
                ('query_params', models.JSONField(help_text='搜尋參數 (page_size, filters, sort, etc.)')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel'), ('xml', 'XML')], db_index=True, help_text='匯出格式', max_length=20)),
                ('include_fields', models.JSONField(blank=True, help_text='選定的匯出欄位清單', null=True)),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], db_index=True, default='pending', help_text='任務當前狀態', max_length=20)),
                ('total_records', models.IntegerField(default=0, help_text='需要匯出的總記錄數')),
                ('processed_records', models.IntegerField(default=0, help_text='已處理的記錄數')),
                ('file_path', models.CharField(blank=True, help_text='本地文件路徑', max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, help_text='文件下載 URL', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='文件大小 (bytes)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='失敗原因描述', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='任務創建時間')),
                ('started_at', models.DateTimeField(blank=True, help_text='處理開始時間', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='處理完成時間', null=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='文件過期時間')),
            ],
            options={
                'verbose_name': '報告匯出任務',
                'verbose_name_plural': '報告匯出任務',
                'db_table': 'report_export_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='report_expo_user_id_00cb9b_idx'), models.Index(fields=['status', 'created_at'], name='report_expo_status_6de5b1_idx'), models.Index(fields=['expires_at'], name='report_expo_expires_b582c0_idx'), models.Index(fields=['export_format', '-created_at'], name='report_expo_export__9150a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('report_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('report_type', models.CharField(db_index=True, max_length=50)),
                ('content_raw', models.TextField()),
                ('content_processed', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('version_number', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('source_url', models.URLField(db_index=True, max_length=500)),
                ('chr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mod', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'one_page_text_report_v2',
                'ordering': ['-verified_at', '-created_at'],
                'indexes': [models.Index(fields=['content_hash', 'verified_at'], name='one_page_te_content_0df575_idx'), models.Index(fields=['source_url', 'verified_at'], name='one_page_te_source__8950ce_idx'), models.Index(fields=['is_latest', '-verified_at'], name='one_page_te_is_late_86bac1_idx'), models.Index(fields=['report_type'], name='one_page_te_report__cfa356_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(db_index=True)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='report.report')),
            ],
            options={
                'verbose_name': 'Report Search Index',
                'verbose_name_plural': 'Report Search Indexes',
                'db_table': 'one_page_text_report_search_index',
            },
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_summary', models.CharField(max_length=500)),
                ('long_summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='report.report')),
            ],
            options={
                'verbose_name': 'Report Summary',
                'verbose_name_plural': 'Report Summaries',
                'db_table': 'one_page_text_report_summaries',
            },
        ),
        migrations.CreateModel(
            name='AIAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annotation_type', models.CharField(db_index=True, max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotations', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='report.report')),
            ],
            options={
                'verbose_name': 'AI Annotation',
                'verbose_name_plural': 'AI Annotations',
                'db_table': 'report_ai_annotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', 'annotation_type'], name='report_ai_a_report__b98221_idx'), models.Index(fields=['created_at'], name='report_ai_a_created_254924_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('content_raw', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('change_description', models.CharField(blank=True, max_length=500)),
                ('change_type', models.CharField(choices=[('create', 'Initial creation'), ('update', 'Content updated'), ('verify', 'Content verified'), ('deduplicate', 'Duplicate consolidated')], default='create', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='report.report')),
            ],
            options={
                'verbose_name': 'Report Version',
                'verbose_name_plural': 'Report Versions',
                'db_table': 'one_page_text_report_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['report', '-version_number'], name='one_page_te_report__e94289_idx'), models.Index(fields=['content_hash'], name='one_page_te_content_8cbb61_idx'), models.Index(fields=['verified_at'], name='one_page_te_verifie_cdacfd_idx')],
                'unique_together': {('report', 'version_number')},
            },
        ),
    ]
