# Generated by Django 5.0 on 2025-11-25 12:34
# Modified: Added conditional operations to handle partial database state

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


def column_exists(connection, table_name, column_name):
    """Check if a column exists in a table."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns
                WHERE table_schema = 'public'
                AND table_name = %s
                AND column_name = %s
            )
        """, [table_name, column_name])
        return cursor.fetchone()[0]


def index_exists(connection, index_name):
    """Check if an index exists in the database."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM pg_indexes
                WHERE indexname = %s
            )
        """, [index_name])
        return cursor.fetchone()[0]


class ConditionalAddField(migrations.AddField):
    """AddField that skips if column already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        if column_exists(schema_editor.connection, table_name, self.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class ConditionalAddIndex(migrations.AddIndex):
    """AddIndex that skips if index already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if index_exists(schema_editor.connection, self.index.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        ConditionalAddField(
            model_name="report",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        ConditionalAddIndex(
            model_name="report",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="one_page_te_search__134beb_gin"
            ),
        ),
    ]
