# Generated by Django 5.2.8 on 2026-02-04 11:14
# Modified: Removed AIAnnotation operations - table doesn't exist in database
# AIAnnotation changes will be handled in a separate migration after table creation

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_improve_generated_columns_with_functions'),
    ]

    operations = [
        # NOTE: All AIAnnotation operations removed - the report_ai_annotations table
        # doesn't exist in the database. These changes will be applied after the table
        # is properly created.

        # ExportTask AlterField operations
        migrations.AlterField(
            model_name='exporttask',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='處理完成時間，當狀態變更為 completed/failed/cancelled 時設置', null=True),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='任務創建時間，自動設定為當前時間'),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='error_message',
            field=models.TextField(blank=True, help_text='失敗原因描述，供用戶和管理員參考', null=True),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='expires_at',
            field=models.DateTimeField(db_index=True, help_text='文件過期時間，用於自動清理任務和文件'),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='export_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel'), ('xml', 'XML')], db_index=True, help_text='匯出格式: csv, json, xlsx, xml', max_length=20),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='file_path',
            field=models.CharField(blank=True, help_text='本地文件存儲路徑', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='file_url',
            field=models.URLField(blank=True, help_text='文件下載 URL，供用戶直接下載', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='include_fields',
            field=models.JSONField(blank=True, help_text='用戶選定的匯出欄位清單', null=True),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='processed_records',
            field=models.IntegerField(default=0, help_text='已處理的記錄數，用於計算進度百分比'),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='query_params',
            field=models.JSONField(help_text='搜尋參數 (page_size, filters, sort 等)'),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='處理開始時間，當狀態變更為 processing 時設置', null=True),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], db_index=True, default='pending', help_text='任務當前狀態: pending, processing, completed, failed, cancelled', max_length=20),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='task_id',
            field=models.CharField(db_index=True, help_text='唯一任務標識，主鍵', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='user_id',
            field=models.CharField(db_index=True, help_text='建立任務的用戶 ID，用於權限控制', max_length=100),
        ),
        # Report AlterField operations
        migrations.AlterField(
            model_name='report',
            name='chr_no',
            field=models.CharField(blank=True, help_text='字符代碼，來自遺留系統', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_hash',
            field=models.CharField(db_index=True, help_text='內容 SHA256 雜湊值，用於快速去重', max_length=64),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_processed',
            field=models.TextField(blank=True, help_text='經正規化處理的報告內容，用於全文搜尋', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='content_raw',
            field=models.TextField(help_text='原始報告內容，完整保存爬蟲結果'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='記錄創建時間戳，自動設定為當前時間'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_latest',
            field=models.BooleanField(db_index=True, default=True, help_text='是否為最新版本，查詢時應優先過濾此欄位'),
        ),
        migrations.AlterField(
            model_name='report',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='動態元資料，儲存額外的特定領域資訊 (JSON 格式)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='mod',
            field=models.CharField(blank=True, help_text='模式/類型代碼，來自遺留系統', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.CharField(blank=True, help_text='報告日期字符串表示', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(blank=True, db_index=True, help_text='系統內部報告編號，用於與外部系統對應', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(db_index=True, help_text='報告格式類型 (PDF, HTML, TXT, XRay, MRI, CT, Ultrasound 等)', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='PostgreSQL 全文搜尋向量，自動生成', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='source_url',
            field=models.URLField(db_index=True, help_text='原始爬蟲來源 URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(db_index=True, help_text='報告標題，用於檢索和展示', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='uid',
            field=models.CharField(db_index=True, help_text='原始爬蟲標識符，為主鍵。相容遺留資料庫中最大 56 字元的 UID', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='記錄更新時間戳，每次修改自動更新'),
        ),
        migrations.AlterField(
            model_name='report',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='報告驗證時間戳，用於排序、去重判定和時間範圍過濾', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='version_number',
            field=models.IntegerField(default=1, help_text='版本號，每次更新內容時遞增'),
        ),
        # ReportSearchIndex AlterField operations
        migrations.AlterField(
            model_name='reportsearchindex',
            name='relevance_score',
            field=models.FloatField(default=1.0, help_text='相關性得分，用於搜尋結果排序，預設值為 1.0'),
        ),
        migrations.AlterField(
            model_name='reportsearchindex',
            name='report',
            field=models.OneToOneField(help_text='與報告的一對一關係，刪除報告時自動級聯刪除索引', on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='report.report'),
        ),
        migrations.AlterField(
            model_name='reportsearchindex',
            name='search_text',
            field=models.TextField(db_index=True, help_text='可搜尋的文本，包含標題 + 處理過的內容 + 元資料'),
        ),
        migrations.AlterField(
            model_name='reportsearchindex',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='索引更新時間戳，每次修改自動更新'),
        ),
        # ReportSummary AlterField operations
        migrations.AlterField(
            model_name='reportsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='摘要建立時間戳'),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='key_points',
            field=models.JSONField(default=list, help_text='關鍵要點列表，JSON 數組格式，如 ["要點1", "要點2", ...]'),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='long_summary',
            field=models.TextField(help_text='詳細摘要，約 500-1000 字'),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='report',
            field=models.OneToOneField(help_text='與報告的一對一關係，刪除報告時自動級聯刪除摘要', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='report.report'),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='short_summary',
            field=models.CharField(help_text='簡短摘要，約 100-200 字', max_length=500),
        ),
        migrations.AlterField(
            model_name='reportsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='摘要更新時間戳，每次修改自動更新'),
        ),
        # ReportVersion AlterField operations
        migrations.AlterField(
            model_name='reportversion',
            name='change_description',
            field=models.CharField(blank=True, help_text='變更描述，簡要說明本次修改內容和原因', max_length=500),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='change_type',
            field=models.CharField(choices=[('create', '初始建立'), ('update', '內容更新'), ('verify', '驗證確認'), ('deduplicate', '去重合併')], default='create', help_text='變更類型: create (初始建立), update (內容更新), verify (驗證確認), deduplicate (去重合併)', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='變更時間戳，自動設定為記錄建立時間'),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='content_hash',
            field=models.CharField(db_index=True, help_text='內容 SHA256 雜湊值快照，追蹤內容變更', max_length=64),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='content_raw',
            field=models.TextField(help_text='報告內容的完整快照，保存版本發佈時的原始內容'),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='report',
            field=models.ForeignKey(help_text='指向父報告記錄，刪除時自動級聯刪除版本', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='report.report'),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='驗證時間戳，追蹤驗證發生的時間點', null=True),
        ),
        migrations.AlterField(
            model_name='reportversion',
            name='version_number',
            field=models.IntegerField(help_text='版本號，與 Report.version_number 對應，組成複合主鍵'),
        ),
    ]
