# Generated by Django 5.0 on 2025-11-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('exam_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('medical_record_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('application_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(db_index=True, max_length=200)),
                ('patient_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=10, null=True)),
                ('patient_birth_date', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('exam_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, max_length=20)),
                ('exam_source', models.CharField(db_index=True, max_length=50)),
                ('exam_item', models.CharField(db_index=True, max_length=200)),
                ('exam_description', models.TextField(blank=True, null=True)),
                ('exam_room', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_equipment', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_type', models.CharField(max_length=100)),
                ('order_datetime', models.DateTimeField(db_index=True)),
                ('check_in_datetime', models.DateTimeField(blank=True, null=True)),
                ('report_certification_datetime', models.DateTimeField(blank=True, null=True)),
                ('certified_physician', models.CharField(blank=True, max_length=200, null=True)),
                ('data_load_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '医疗研究',
                'verbose_name_plural': '医疗研究',
                'db_table': 'medical_examinations_fact',
                'ordering': ['-order_datetime'],
                'indexes': [models.Index(fields=['exam_status', '-order_datetime'], name='medical_exa_exam_st_78be2b_idx'), models.Index(fields=['exam_source', '-order_datetime'], name='medical_exa_exam_so_a670bd_idx'), models.Index(fields=['patient_name'], name='medical_exa_patient_a671d9_idx'), models.Index(fields=['exam_item'], name='medical_exa_exam_it_d72ca8_idx')],
            },
        ),
    ]
