# Generated by Django 5.0 on 2025-11-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uid', models.CharField(db_index=True, max_length=32, primary_key=True, serialize=False)),
                ('report_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('report_type', models.CharField(db_index=True, max_length=50)),
                ('content_raw', models.TextField()),
                ('content_processed', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('version_number', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('source_url', models.URLField(db_index=True, max_length=500)),
                ('chr_no', models.CharField(blank=True, max_length=100, null=True)),
                ('mod', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'one_page_text_report_v2',
                'ordering': ['-verified_at', '-created_at'],
                'indexes': [models.Index(fields=['content_hash', 'verified_at'], name='one_page_te_content_0df575_idx'), models.Index(fields=['source_url', 'verified_at'], name='one_page_te_source__8950ce_idx'), models.Index(fields=['is_latest', '-verified_at'], name='one_page_te_is_late_86bac1_idx'), models.Index(fields=['report_type'], name='one_page_te_report__cfa356_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(db_index=True)),
                ('relevance_score', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='studies.report')),
            ],
            options={
                'verbose_name': 'Report Search Index',
                'verbose_name_plural': 'Report Search Indexes',
                'db_table': 'one_page_text_report_search_index',
            },
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_summary', models.CharField(max_length=500)),
                ('long_summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='studies.report')),
            ],
            options={
                'verbose_name': 'Report Summary',
                'verbose_name_plural': 'Report Summaries',
                'db_table': 'one_page_text_report_summaries',
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('content_raw', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('change_description', models.CharField(blank=True, max_length=500)),
                ('change_type', models.CharField(choices=[('create', 'Initial creation'), ('update', 'Content updated'), ('verify', 'Content verified'), ('deduplicate', 'Duplicate consolidated')], default='create', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='studies.report')),
            ],
            options={
                'verbose_name': 'Report Version',
                'verbose_name_plural': 'Report Versions',
                'db_table': 'one_page_text_report_versions',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['report', '-version_number'], name='one_page_te_report__e94289_idx'), models.Index(fields=['content_hash'], name='one_page_te_content_8cbb61_idx'), models.Index(fields=['verified_at'], name='one_page_te_verifie_cdacfd_idx')],
                'unique_together': {('report', 'version_number')},
            },
        ),
    ]
