# Generated by Django 4.2 on 2024-11-12
# Migration for AI Validation Workflow System

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0001_initial'),
    ]

    operations = [
        # 1. 驗證工作流總表
        migrations.CreateModel(
            name='VerificationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, help_text='工作流名稱')),
                ('study_type', models.CharField(max_length=50, help_text='檢查類型 (Aorta CTA, Brain MRI, etc.)')),
                ('status', models.CharField(
                    max_length=20,
                    default='draft',
                    choices=[
                        ('draft', '草稿'),
                        ('pacs_searching', 'PACS搜尋中'),
                        ('llm_analyzing', 'LLM分析中'),
                        ('physician_review', '醫師審核中'),
                        ('sampling', '抽樣中'),
                        ('completed', '已完成'),
                        ('failed', '失敗'),
                    ]
                )),

                # PACS搜尋條件
                ('pacs_search_criteria', models.JSONField(default=dict, help_text='PACS搜尋條件')),
                ('pacs_study_count', models.IntegerField(null=True, blank=True)),

                # LLM配置
                ('llm_prompt_template', models.TextField(blank=True, help_text='LLM提示模板')),
                ('llm_model', models.CharField(max_length=50, default='qwen2.5:7b')),

                # 醫師審核配置
                ('sampling_strategy', models.JSONField(default=dict, help_text='抽樣策略配置')),
                ('guideline_version', models.CharField(max_length=50, blank=True)),
                ('current_guideline', models.TextField(blank=True)),

                # 進度追蹤
                ('phase', models.CharField(max_length=50, blank=True, help_text='當前執行階段')),
                ('progress_data', models.JSONField(default=dict, help_text='各階段進度細節')),

                # 元資料
                ('created_by', models.ForeignKey(
                    settings.AUTH_USER_MODEL,
                    on_delete=models.SET_NULL,
                    null=True,
                    related_name='created_workflows'
                )),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'verbose_name': '驗證工作流',
                'verbose_name_plural': '驗證工作流',
                'ordering': ['-created_at'],
            },
        ),

        # 2. PACS Study清單
        migrations.CreateModel(
            name='PACSStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.ForeignKey(
                    on_delete=models.CASCADE,
                    to='studies.VerificationWorkflow',
                    related_name='pacs_studies'
                )),

                # DICOM識別資訊
                ('study_instance_uid', models.CharField(max_length=255, unique=True)),
                ('accession_number', models.CharField(max_length=50, blank=True)),
                ('patient_id', models.CharField(max_length=50, help_text='原始Patient ID')),
                ('patient_name', models.CharField(max_length=200, blank=True)),

                # Study基本資訊
                ('study_date', models.DateField(null=True, blank=True)),
                ('study_time', models.TimeField(null=True, blank=True)),
                ('modality', models.CharField(max_length=10, help_text='CT, MRI, CR, etc.')),
                ('body_part', models.CharField(max_length=100, blank=True)),
                ('study_description', models.TextField(blank=True)),

                # 報告內容
                ('report_text', models.TextField(blank=True, help_text='從PACS抓取的報告文字')),
                ('report', models.ForeignKey(
                    to='studies.Report',
                    on_delete=models.SET_NULL,
                    null=True,
                    blank=True,
                    help_text='連結到現有reports表'
                )),

                # 處理狀態
                ('status', models.CharField(
                    max_length=20,
                    default='pending',
                    choices=[
                        ('pending', '待處理'),
                        ('llm_analyzed', 'LLM已分析'),
                        ('physician_reviewed', '醫師已審核'),
                        ('approved', '已核准'),
                        ('rejected', '已拒絕'),
                        ('exported', '已匯出'),
                    ]
                )),

                # LLM判讀結果
                ('llm_result', models.JSONField(default=dict, blank=True)),
                ('llm_analyzed_at', models.DateTimeField(null=True, blank=True)),

                # 醫師審核
                ('physician_review', models.JSONField(default=dict, blank=True)),
                ('final_decision', models.CharField(
                    max_length=20,
                    blank=True,
                    choices=[
                        ('approved', '核准'),
                        ('rejected', '拒絕'),
                        ('fp_confirmed', '確認為FP'),
                    ]
                )),

                # DICOM處理
                ('dicom_files_path', models.CharField(max_length=500, blank=True)),
                ('anonymized_patient_id', models.CharField(max_length=50, blank=True)),
                ('nifti_path', models.CharField(max_length=500, blank=True)),
                ('export_status', models.CharField(
                    max_length=20,
                    blank=True,
                    choices=[
                        ('pending', '待處理'),
                        ('downloading', '下載中'),
                        ('anonymizing', '匿名化中'),
                        ('converting', '轉換中'),
                        ('completed', '已完成'),
                    ]
                )),

                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PACS Study',
                'verbose_name_plural': 'PACS Studies',
                'ordering': ['-study_date', '-created_at'],
            },
        ),

        # 3. LLM判讀結果詳細表
        migrations.CreateModel(
            name='LLMAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(
                    on_delete=models.CASCADE,
                    to='studies.PACSStudy',
                    related_name='llm_analyses'
                )),
                ('workflow', models.ForeignKey(
                    on_delete=models.CASCADE,
                    to='studies.VerificationWorkflow',
                    related_name='llm_results'
                )),

                # 判讀輸入
                ('prompt_used', models.TextField()),
                ('report_text', models.TextField()),

                # 判讀輸出
                ('classification', models.CharField(
                    max_length=50,
                    choices=[
                        ('no_disease', '無疾病'),
                        ('uncertain', '無信心'),
                        ('has_disease', '有疾病'),
                    ]
                )),
                ('confidence_score', models.DecimalField(max_digits=3, decimal_places=2)),
                ('key_findings', models.JSONField(default=list)),
                ('disease_markers', models.JSONField(default=list)),

                # 統計分類
                ('is_disease_case', models.BooleanField(default=False)),
                ('is_uncertain_case', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),

                # LLM技術資訊
                ('model_used', models.CharField(max_length=50)),
                ('inference_time_ms', models.IntegerField(null=True, blank=True)),
                ('tokens_used', models.IntegerField(null=True, blank=True)),

                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'LLM分析結果',
                'verbose_name_plural': 'LLM分析結果',
                'ordering': ['-created_at'],
            },
        ),

        # 4. 醫師審核記錄表
        migrations.CreateModel(
            name='PhysicianReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(
                    on_delete=models.CASCADE,
                    to='studies.PACSStudy',
                    related_name='physician_reviews'
                )),
                ('workflow', models.ForeignKey(
                    on_delete=models.CASCADE,
                    to='studies.VerificationWorkflow',
                    related_name='physician_reviews'
                )),
                ('reviewer', models.ForeignKey(
                    settings.AUTH_USER_MODEL,
                    on_delete=models.SET_NULL,
                    null=True,
                    related_name='validation_reviews'
                )),

                # 審核類型
                ('review_type', models.CharField(
                    max_length=20,
                    choices=[
                        ('random_sampling', '隨機抽樣'),
                        ('fp_check', 'FP檢查'),
                        ('uncertain_case', '不確定案例'),
                    ]
                )),

                # 審核結果
                ('decision', models.CharField(
                    max_length=20,
                    choices=[
                        ('approve', '核准'),
                        ('reject', '拒絕'),
                        ('uncertain', '不確定'),
                    ]
                )),
                ('is_false_positive', models.BooleanField(default=False)),
                ('is_guideline_violation', models.BooleanField(default=False)),

                # 審核意見
                ('review_notes', models.TextField(blank=True)),
                ('suggested_guideline_update', models.TextField(blank=True)),

                # 影像相關
                ('viewed_images', models.BooleanField(default=False)),
                ('image_quality_score', models.IntegerField(
                    null=True, blank=True,
                    choices=[(i, i) for i in range(1, 6)]  # 1-5分
                )),

                # 時間記錄
                ('review_started_at', models.DateTimeField(null=True, blank=True)),
                ('review_completed_at', models.DateTimeField(null=True, blank=True)),
                ('review_duration_seconds', models.IntegerField(null=True, blank=True)),

                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '醫師審核',
                'verbose_name_plural': '醫師審核',
                'ordering': ['-created_at'],
            },
        ),

        # 5. Guideline版本管理表
        migrations.CreateModel(
            name='GuidelineVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.ForeignKey(
                    on_delete=models.CASCADE,
                    to='studies.VerificationWorkflow',
                    related_name='guideline_versions'
                )),

                ('version', models.CharField(max_length=20)),
                ('guideline_text', models.TextField()),

                # 變更追蹤
                ('changes_from_previous', models.TextField(blank=True)),
                ('reason_for_update', models.TextField(blank=True)),

                # FP案例觸發
                ('triggered_by_fp_cases', models.JSONField(default=list, help_text='觸發此更新的FP案例ID列表')),

                # 版本狀態
                ('status', models.CharField(
                    max_length=20,
                    default='draft',
                    choices=[
                        ('draft', '草稿'),
                        ('active', '啟用中'),
                        ('archived', '已歸檔'),
                    ]
                )),
                ('activated_at', models.DateTimeField(null=True, blank=True)),

                ('created_by', models.ForeignKey(
                    settings.AUTH_USER_MODEL,
                    on_delete=models.SET_NULL,
                    null=True,
                    related_name='created_guidelines'
                )),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Guideline版本',
                'verbose_name_plural': 'Guideline版本',
                'ordering': ['-created_at'],
            },
        ),

        # 建立索引
        migrations.AddIndex(
            model_name='verificationworkflow',
            index=models.Index(fields=['status'], name='idx_workflow_status'),
        ),
        migrations.AddIndex(
            model_name='pacsstudy',
            index=models.Index(fields=['workflow'], name='idx_studies_workflow'),
        ),
        migrations.AddIndex(
            model_name='pacsstudy',
            index=models.Index(fields=['status'], name='idx_studies_status'),
        ),
        migrations.AddIndex(
            model_name='pacsstudy',
            index=models.Index(fields=['study_instance_uid'], name='idx_studies_uid'),
        ),
        migrations.AddIndex(
            model_name='llmanalysisresult',
            index=models.Index(fields=['study'], name='idx_llm_results_study'),
        ),
        migrations.AddIndex(
            model_name='physicianreview',
            index=models.Index(fields=['workflow'], name='idx_reviews_workflow'),
        ),
        migrations.AddIndex(
            model_name='physicianreview',
            index=models.Index(fields=['reviewer'], name='idx_reviews_reviewer'),
        ),
    ]