# Generated by Django 5.0 on 2025-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_report_reportsearchindex_reportsummary_reportversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='uid',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
