# Generated by Django 5.0 on 2025-11-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_add_validation_workflow_tables'),
        ('studies', '0003_alter_report_uid'),
    ]

    operations = [
    ]
