# Generated by Django 5.0 on 2025-11-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_merge_20251112_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('task_id', models.CharField(db_index=True, help_text='唯一任務標識', max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='創建用戶 ID', max_length=100)),
                ('query_params', models.JSONField(help_text='搜尋參數 (page_size, filters, sort, etc.)')),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel'), ('xml', 'XML')], db_index=True, help_text='匯出格式', max_length=20)),
                ('include_fields', models.JSONField(blank=True, help_text='選定的匯出欄位清單', null=True)),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], db_index=True, default='pending', help_text='任務當前狀態', max_length=20)),
                ('total_records', models.IntegerField(default=0, help_text='需要匯出的總記錄數')),
                ('processed_records', models.IntegerField(default=0, help_text='已處理的記錄數')),
                ('file_path', models.CharField(blank=True, help_text='本地文件路徑', max_length=500, null=True)),
                ('file_url', models.URLField(blank=True, help_text='文件下載 URL', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='文件大小 (bytes)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='失敗原因描述', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='任務創建時間')),
                ('started_at', models.DateTimeField(blank=True, help_text='處理開始時間', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='處理完成時間', null=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='文件過期時間')),
            ],
            options={
                'verbose_name': '報告匯出任務',
                'verbose_name_plural': '報告匯出任務',
                'db_table': 'report_export_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='report_expo_user_id_00cb9b_idx'), models.Index(fields=['status', 'created_at'], name='report_expo_status_6de5b1_idx'), models.Index(fields=['expires_at'], name='report_expo_expires_b582c0_idx'), models.Index(fields=['export_format', '-created_at'], name='report_expo_export__9150a9_idx')],
            },
        ),
    ]
