# Generated by Django 5.0 on 2025-11-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_add_export_task_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmanalysisresult',
            name='study',
        ),
        migrations.RemoveField(
            model_name='llmanalysisresult',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='pacsstudy',
            name='report',
        ),
        migrations.RemoveField(
            model_name='pacsstudy',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='physicianreview',
            name='study',
        ),
        migrations.RemoveField(
            model_name='physicianreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='physicianreview',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='verificationworkflow',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='GuidelineVersion',
        ),
        migrations.DeleteModel(
            name='LLMAnalysisResult',
        ),
        migrations.DeleteModel(
            name='PACSStudy',
        ),
        migrations.DeleteModel(
            name='PhysicianReview',
        ),
        migrations.DeleteModel(
            name='VerificationWorkflow',
        ),
    ]
