# Generated by Django 5.0 on 2025-11-13 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_add_project_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='專案ID'),
        ),
        migrations.AlterField(
            model_name='studyprojectassignment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='studies.study', verbose_name='研究'),
        ),
    ]
