# Generated by Django 5.2.8 on 2026-02-04 11:14
# Modified: Added conditional table creation to handle partial database state

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def table_exists(connection, table_name):
    """Check if a table exists in the database."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = %s
            )
        """, [table_name])
        return cursor.fetchone()[0]


def index_exists(connection, index_name):
    """Check if an index exists in the database."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM pg_indexes
                WHERE indexname = %s
            )
        """, [index_name])
        return cursor.fetchone()[0]


class ConditionalCreateModel(migrations.CreateModel):
    """CreateModel that skips if table already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        table_name = self.options.get('db_table', f"{app_label}_{self.name.lower()}")
        if table_exists(schema_editor.connection, table_name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class ConditionalAddIndex(migrations.AddIndex):
    """AddIndex that skips if index already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if index_exists(schema_editor.connection, self.index.name):
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '__first__'),
        ('report', '0010_create_aiannotation_with_new_fields'),  # Depends on AIAnnotation table
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        ConditionalCreateModel(
            name='ClassificationGuideline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='指南ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='指南名稱')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('prompt_template', models.TextField(help_text='支援變數: {{content_raw}}, {{imaging_findings}}, {{impression}}', verbose_name='Prompt 模板')),
                ('categories', models.JSONField(default=list, help_text='分類標籤列表，例如: ["positive", "negative", "uncertain"]', verbose_name='分類類別')),
                ('version', models.IntegerField(default=1, verbose_name='版本號')),
                ('is_current', models.BooleanField(db_index=True, default=True, verbose_name='是否為當前版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('testing', '測試中'), ('approved', '已核准'), ('archived', '已封存')], db_index=True, default='draft', max_length=20, verbose_name='狀態')),
                ('model_config', models.JSONField(blank=True, default=dict, help_text='LLM 參數配置，如 temperature, model_name 等', verbose_name='模型配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核准時間')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_guidelines', to=settings.AUTH_USER_MODEL, verbose_name='核准者')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_guidelines', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='ai.classificationguideline', verbose_name='父版本')),
            ],
            options={
                'verbose_name': '分類指南',
                'verbose_name_plural': '分類指南',
                'db_table': 'ai_classification_guidelines',
                'ordering': ['-updated_at'],
            },
        ),
        ConditionalCreateModel(
            name='BatchAnalysisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任務ID')),
                ('report_uids', models.JSONField(default=list, help_text='要分析的報告 UID 陣列', verbose_name='報告 UID 列表')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='狀態')),
                ('total_count', models.IntegerField(default=0, verbose_name='總數')),
                ('processed_count', models.IntegerField(default=0, verbose_name='已處理數')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功數')),
                ('error_count', models.IntegerField(default=0, verbose_name='錯誤數')),
                ('funboost_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Funboost 任務 ID')),
                ('results_summary', models.JSONField(blank=True, default=dict, help_text='各分類類別的統計計數', verbose_name='結果摘要')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='失敗報告的錯誤資訊列表', verbose_name='錯誤詳情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_batch_tasks', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_analysis_tasks', to='project.project', verbose_name='所屬專案')),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_tasks', to='ai.classificationguideline', verbose_name='分類指南')),
            ],
            options={
                'verbose_name': '批次分析任務',
                'verbose_name_plural': '批次分析任務',
                'db_table': 'ai_batch_analysis_tasks',
                'ordering': ['-created_at'],
            },
        ),
        ConditionalCreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='模板ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='模板名稱')),
                ('content', models.TextField(verbose_name='模板內容')),
                ('category', models.CharField(choices=[('report_analysis', '報告分析'), ('exam_query', '檢查查詢'), ('term_explanation', '術語解釋'), ('data_extraction', '數據提取'), ('severity_assessment', '嚴重程度評估'), ('general', '一般')], db_index=True, default='general', max_length=50, verbose_name='分類')),
                ('use_case', models.CharField(choices=[('report_analysis', '報告分析'), ('exam_query', '檢查查詢'), ('term_explanation', '術語解釋'), ('data_extraction', '數據提取'), ('severity_assessment', '嚴重程度評估'), ('general', '一般')], db_index=True, default='general', max_length=50, verbose_name='使用案例')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否啟用')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_prompt_templates', to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
            ],
            options={
                'verbose_name': '提示詞模板',
                'verbose_name_plural': '提示詞模板',
                'db_table': 'prompt_templates',
                'ordering': ['-updated_at'],
            },
        ),
        ConditionalCreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='分配ID')),
                ('role', models.CharField(choices=[('primary', '主審'), ('secondary', '副審'), ('arbitrator', '仲裁者')], default='primary', max_length=20, verbose_name='角色')),
                ('completed_samples', models.IntegerField(default=0, verbose_name='已完成樣本數')),
                ('total_assigned', models.IntegerField(default=0, verbose_name='分配樣本總數')),
                ('can_view_others', models.BooleanField(default=False, help_text='雙盲模式下應設為 False', verbose_name='可查看其他審核者結果')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配時間')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL, verbose_name='審核者')),
            ],
            options={
                'verbose_name': '審核者分配',
                'verbose_name_plural': '審核者分配',
                'db_table': 'ai_reviewer_assignments',
                'ordering': ['review_task', 'role'],
            },
        ),
        ConditionalCreateModel(
            name='ReviewSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='樣本ID')),
                ('stratum', models.CharField(blank=True, default='', help_text='抽樣時的分層標籤，如 "exam_source:CT"', max_length=100, verbose_name='分層標籤')),
                ('ai_classification', models.CharField(help_text='抽樣時的 AI 分類結果快照', max_length=50, verbose_name='AI 分類結果')),
                ('ai_confidence', models.FloatField(blank=True, help_text='抽樣時的 AI 信心度分數 (0.0-1.0)', null=True, verbose_name='AI 信心度')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('needs_second_review', '需要第二審核'), ('in_arbitration', '仲裁中'), ('completed', '已完成')], db_index=True, default='pending', max_length=20, verbose_name='狀態')),
                ('final_is_correct', models.BooleanField(blank=True, null=True, verbose_name='最終判定是否正確')),
                ('final_correct_category', models.CharField(blank=True, help_text='若 AI 分類錯誤，此欄位記錄正確分類', max_length=50, null=True, verbose_name='最終正確分類')),
                ('ai_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_samples', to='report.aiannotation', verbose_name='AI 註解')),
                ('final_determined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='determined_samples', to=settings.AUTH_USER_MODEL, verbose_name='最終判定者')),
            ],
            options={
                'verbose_name': '審核樣本',
                'verbose_name_plural': '審核樣本',
                'db_table': 'ai_review_samples',
                'ordering': ['review_task', 'stratum'],
            },
        ),
        ConditionalCreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='回饋ID')),
                ('is_correct', models.BooleanField(verbose_name='AI 分類是否正確')),
                ('correct_category', models.CharField(blank=True, help_text='若 AI 分類錯誤，此欄位記錄正確分類', max_length=50, null=True, verbose_name='正確分類')),
                ('confidence_level', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='high', max_length=20, verbose_name='信心程度')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備註')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交時間')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='審核者')),
                ('reviewer_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai.reviewerassignment', verbose_name='審核者分配')),
                ('review_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai.reviewsample', verbose_name='審核樣本')),
            ],
            options={
                'verbose_name': '審核回饋',
                'verbose_name_plural': '審核回饋',
                'db_table': 'ai_review_feedbacks',
                'ordering': ['-submitted_at'],
            },
        ),
        ConditionalCreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='審核任務ID')),
                ('name', models.CharField(max_length=200, verbose_name='任務名稱')),
                ('sample_size', models.IntegerField(help_text='要抽樣的報告數量', verbose_name='樣本數')),
                ('sampling_config', models.JSONField(blank=True, default=dict, help_text='抽樣策略配置，如分層欄位、權重等', verbose_name='抽樣配置')),
                ('review_mode', models.CharField(choices=[('single', '單人審閱'), ('double_blind', '雙盲審閱')], default='single', max_length=20, verbose_name='審核模式')),
                ('required_reviewers', models.IntegerField(default=1, verbose_name='所需審核者數')),
                ('fp_threshold', models.FloatField(default=0.2, help_text='False Positive 比例閾值，超過則需要重新訓練', verbose_name='FP 閾值')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('in_progress', '進行中'), ('arbitration', '仲裁中'), ('completed', '已完成')], db_index=True, default='pending', max_length=20, verbose_name='狀態')),
                ('fp_rate', models.FloatField(blank=True, null=True, verbose_name='FP 率')),
                ('agreement_rate', models.FloatField(blank=True, help_text="Cohen's Kappa 或其他一致性指標", null=True, verbose_name='一致性率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('batch_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='ai.batchanalysistask', verbose_name='批次分析任務')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_review_tasks', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '審核任務',
                'verbose_name_plural': '審核任務',
                'db_table': 'ai_review_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reviewsample',
            name='review_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='ai.reviewtask', verbose_name='審核任務'),
        ),
        migrations.AddField(
            model_name='reviewerassignment',
            name='review_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ai.reviewtask', verbose_name='審核任務'),
        ),
        ConditionalAddIndex(
            model_name='classificationguideline',
            index=models.Index(fields=['status', '-updated_at'], name='idx_guideline_status_updated'),
        ),
        ConditionalAddIndex(
            model_name='classificationguideline',
            index=models.Index(fields=['is_current', '-version'], name='idx_guideline_current_version'),
        ),
        ConditionalAddIndex(
            model_name='classificationguideline',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_guideline_creator'),
        ),
        ConditionalAddIndex(
            model_name='classificationguideline',
            index=models.Index(fields=['name', 'is_current'], name='idx_guideline_name_current'),
        ),
        ConditionalAddIndex(
            model_name='batchanalysistask',
            index=models.Index(fields=['status', '-created_at'], name='idx_batch_status_created'),
        ),
        ConditionalAddIndex(
            model_name='batchanalysistask',
            index=models.Index(fields=['guideline', '-created_at'], name='idx_batch_guideline_created'),
        ),
        ConditionalAddIndex(
            model_name='batchanalysistask',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_batch_creator_created'),
        ),
        ConditionalAddIndex(
            model_name='batchanalysistask',
            index=models.Index(fields=['project', '-created_at'], name='idx_batch_project_created'),
        ),
        ConditionalAddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['category', '-updated_at'], name='idx_pt_category_updated'),
        ),
        ConditionalAddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['use_case', '-updated_at'], name='idx_pt_usecase_updated'),
        ),
        ConditionalAddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_pt_creator_created'),
        ),
        ConditionalAddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['is_active', '-updated_at'], name='idx_pt_active_updated'),
        ),
        ConditionalAddIndex(
            model_name='reviewfeedback',
            index=models.Index(fields=['review_sample', 'reviewer'], name='idx_feedback_sample_reviewer'),
        ),
        ConditionalAddIndex(
            model_name='reviewfeedback',
            index=models.Index(fields=['reviewer_assignment'], name='idx_feedback_assignment'),
        ),
        ConditionalAddIndex(
            model_name='reviewfeedback',
            index=models.Index(fields=['is_correct'], name='idx_feedback_is_correct'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewfeedback',
            unique_together={('review_sample', 'reviewer')},
        ),
        ConditionalAddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['status', '-created_at'], name='idx_review_status_created'),
        ),
        ConditionalAddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['batch_task', '-created_at'], name='idx_review_batch_created'),
        ),
        ConditionalAddIndex(
            model_name='reviewtask',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_review_creator_created'),
        ),
        ConditionalAddIndex(
            model_name='reviewsample',
            index=models.Index(fields=['review_task', 'status'], name='idx_sample_task_status'),
        ),
        ConditionalAddIndex(
            model_name='reviewsample',
            index=models.Index(fields=['ai_annotation'], name='idx_sample_annotation'),
        ),
        ConditionalAddIndex(
            model_name='reviewsample',
            index=models.Index(fields=['stratum'], name='idx_sample_stratum'),
        ),
        ConditionalAddIndex(
            model_name='reviewerassignment',
            index=models.Index(fields=['review_task', 'role'], name='idx_assignment_task_role'),
        ),
        ConditionalAddIndex(
            model_name='reviewerassignment',
            index=models.Index(fields=['reviewer'], name='idx_assignment_reviewer'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewerassignment',
            unique_together={('review_task', 'reviewer')},
        ),
    ]
